/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import views.panels.newPanel_cotizaciones;
import views.panels.panel_inventory;

/**
 *
 * @author jo29h
 */
public class Menu_Empleados_View extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Empleados_View
     */
    public Menu_Empleados_View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        PanelDinamyc = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        PanelButtonCotizacion = new javax.swing.JPanel();
        LabelButtonCotizacion = new javax.swing.JLabel();
        panelInventary = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        returnLoginView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(0, 0, 51));
        PanelPrincipal.setMinimumSize(new java.awt.Dimension(1910, 1000));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelDinamyc.setBackground(new java.awt.Color(0, 0, 51));
        PanelDinamyc.setPreferredSize(new java.awt.Dimension(1352, 1011));

        javax.swing.GroupLayout PanelDinamycLayout = new javax.swing.GroupLayout(PanelDinamyc);
        PanelDinamyc.setLayout(PanelDinamycLayout);
        PanelDinamycLayout.setHorizontalGroup(
            PanelDinamycLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1610, Short.MAX_VALUE)
        );
        PanelDinamycLayout.setVerticalGroup(
            PanelDinamycLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        PanelPrincipal.add(PanelDinamyc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 1000));

        jPanel2.setBackground(new java.awt.Color(51, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelButtonCotizacion.setBackground(new java.awt.Color(0, 0, 102));

        LabelButtonCotizacion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LabelButtonCotizacion.setForeground(new java.awt.Color(255, 255, 255));
        LabelButtonCotizacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelButtonCotizacion.setText("Cotizacion de producto");
        LabelButtonCotizacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelButtonCotizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LabelButtonCotizacionMousePressed(evt);
            }
        });

        javax.swing.GroupLayout PanelButtonCotizacionLayout = new javax.swing.GroupLayout(PanelButtonCotizacion);
        PanelButtonCotizacion.setLayout(PanelButtonCotizacionLayout);
        PanelButtonCotizacionLayout.setHorizontalGroup(
            PanelButtonCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelButtonCotizacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelButtonCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelButtonCotizacionLayout.setVerticalGroup(
            PanelButtonCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelButtonCotizacionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LabelButtonCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(PanelButtonCotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, 50));

        panelInventary.setBackground(new java.awt.Color(0, 0, 102));
        panelInventary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelInventaryMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("             Inventario");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelInventaryLayout = new javax.swing.GroupLayout(panelInventary);
        panelInventary.setLayout(panelInventaryLayout);
        panelInventaryLayout.setHorizontalGroup(
            panelInventaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInventaryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelInventaryLayout.setVerticalGroup(
            panelInventaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInventaryLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(panelInventary, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, 50));

        returnLoginView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/view_exit.png"))); // NOI18N
        returnLoginView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnLoginViewActionPerformed(evt);
            }
        });
        jPanel2.add(returnLoginView, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 70, 80));

        PanelPrincipal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 10, 230, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LabelButtonCotizacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelButtonCotizacionMousePressed
        newPanel_cotizaciones PanelCotizaciones = new newPanel_cotizaciones();
        ShowPanel(PanelCotizaciones);
    }//GEN-LAST:event_LabelButtonCotizacionMousePressed

    private void panelInventaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelInventaryMouseClicked
        // CLICK DEL SEGUNDO BOTON 
    }//GEN-LAST:event_panelInventaryMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        panel_inventory PanelInventary = new panel_inventory();
        ShowPanel(PanelInventary);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void returnLoginViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnLoginViewActionPerformed
        Login_View LV = new Login_View();
        LV.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_returnLoginViewActionPerformed

    private void ShowPanel(JPanel p) {
        p.setSize(1600, 1011);
        p.setLocation(0, 0);

        PanelDinamyc.removeAll();
        PanelDinamyc.add(p, BorderLayout.CENTER);
        PanelDinamyc.revalidate();
        PanelDinamyc.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Empleados_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Empleados_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Empleados_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Empleados_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Empleados_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelButtonCotizacion;
    private javax.swing.JPanel PanelButtonCotizacion;
    private javax.swing.JPanel PanelDinamyc;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelInventary;
    private javax.swing.JButton returnLoginView;
    // End of variables declaration//GEN-END:variables
}
